### ISSUE TITLE
can you make a LineageOS 19 for rpi3 

### ISSUE THREAD

**Issue by haotian2004** [lineage-rpi/OTA#2]
because i don·t have rpi4

**Comment by KonstaT** [comment]
No, I've retired my Pi 3 from development ages ago. Hardware specs on the Pi 3 match low end Android devices from ~7 years ago and Pi only has 512mb of RAM (shared with GPU) which is nowhere enough for recent Android versions.

Existing Pi 3 builds are available at https://konstakang.com/devices/rpi3/.
