### ISSUE TITLE
Audio issue LineageOS 20 20240111 Android TV RPi4

### ISSUE THREAD

**Issue by xoxopeter** [lineage-rpi/OTA#3]
Hi Konsta,

I have an issue with the lineageOS 20 Android tv version (LineageOS 20 20240111 Android TV) on raspberry pi 4.

After doing some tests, switching av and reboot I no longer have the sound. 

I tried several manipulations but impossible to get the sound back. Maybe anyone else had the same issue?

Do you have a workaround please (other than reset the PI and doing the install again) ? Or is an update planned?

Regards,

**Comment by KonstaT** [comment]
Closing as this is not the right place for this.

Trace your own steps what you've changed since it worked before.
